### ISSUE TITLE
problem at the path forum image with virtual folder

### ISSUE THREAD

**Issue by phpbb-store** [phpbb-seo/usu#1]
problem with the path image. the "./" path is not recognized.
forum image not show. 
![screen](https://user-images.githubusercontent.com/15216973/34083281-d9e3b89a-e36d-11e7-9e61-bdd56b2fa58b.jpg)
![screen2ok](https://user-images.githubusercontent.com/15216973/34083284-ddd17c12-e36d-11e7-95b9-387e50f43fad.jpg)

**Comment by Persian-phpBB** [comment]
i tested in http://www.phpbb-seo.org/community/ no problem ...

**Comment by phpbb-store** [comment]
see this: http://www.phpbb-seo.org/community/general/

**Comment by thetopfew** [comment]
Replace the src= in browser with this: src="http://phpbb-seo.org/community/././images/icons/announcement_icon.png"

Notice, I only added your forum domain to it. That's exactly what it's missing ($this->phpbb_root_path), regardless of it not being totally accurate in this example, it proves what you need to add, just not where yet. Wherever the '/././' is injected, that's where it is. Perhaps it's in your regex.

**Comment by Persian-phpBB** [comment]
not working in htaccess 
         # FIX RELATIVE PATHS : IMAGES
         RewriteRule ^(styles/.*|images/.*|assets/.*|ext/.*)$ $1 [QSA,L,NC,R=301]
         RewriteRule ^.+/(styles/.|images/.)/$ /community/$1 [QSA,L,NC,R=301]

**Comment by Erwane** [comment]
I have same problem : 
https://myrnbarad.org/recrutement/

the "World of Warcraft" icon path is set to $phpbb_root_path which is `./` instead of `/`

**Comment by phpbb-store** [comment]
good morning. this problem has been fixed in beta 4?
