### ISSUE TITLE
Little concern

### ISSUE THREAD

**Issue by germansassone** [phpbb-seo/usu#10]
I am trying your extension with certain satisfaction I might add

I may have found something to improve, If It's not my fault

I've noticed that my forum after installing usu, is very slow on firefox, but on chrome is like a Ferrari

Would I have done something wrong? Or there is something I can do about It?

Thanks. And btw good work.

**Comment by olalavui** [comment]
I think it's just your personal feeling. Please check back in F12 (Console) to see if there are any errors in the browser you use to get a more specific solution.
