### ISSUE TITLE
problem in acp / usu.php (beta 4)

### ISSUE THREAD

**Issue by phpbb-store** [phpbb-seo/usu#18]
after installation, clicking on the acp / phpbb seo tab, I get this error:
Fatal error: Call to a member function lang() on a non-object in C:\xampp\htdocs\phpbbstore32\ext\phpbbseo\usu\acp\usu.php on line 145

**Comment by meis2m** [comment]
Hi
what is your php version?

**Comment by phpbb-store** [comment]
I have php 5.6.39

**Comment by phpbb-store** [comment]
edit:
the test was done on phpbb 3.2.1
I have now tried a new phpbb 3.2.7 installation and it works.
