### ISSUE TITLE
thanks for posts vs seo url

### ISSUE THREAD

**Issue by CristiOprea** [phpbb-seo/usu#2]
github seo url: https://github.com/phpbb-seo/usu/
thanks for posts github url: https://github.com/Naguissa/thanks_for_posts/tree/master/gfksx/ThanksForPosts

This modified doesn't work for me! 
A for me working variant with phpbb 3.1.8 and Thanks for Posts from 16.01.2016 and usu from 9.08.2015:
In /ext/phpbbseo/usu/event/listener.php look for

if ($post_id && !$view && !$this->core->set_do_redir_post())

replace with

// Thanks for Posts extension
                    $to_id = request_var('to_id', 0);
                    $thanks = request_var('thanks', 0);
                    $rthanks = request_var('rthanks', 0);
//                  if ($post_id && !$view && !$this->core->set_do_redir_post())
                        if (($rthanks || $thanks || $post_id)  && !$view && $this->core->set_do_redir_post())
// Thanks for Posts extension

Then look for
'hilit' => array('val' => (($highlight_match) ? $highlight : ''), 'keep' => !empty($highlight_match)),

And add after

// Thanks for Posts extension
                            'rthanks' => array('val' => $rthanks, 'keep' => $rthanks),
                            'to_id' => array('val' => $to_id, 'keep' => $to_id),
                            'thanks' => array('val' => $thanks, 'keep' => $thanks),
// Thanks for Posts extension

then look for $this->core->zero_dupe();

and replace with

// Thanks for Posts extension
//                  $this->core->zero_dupe();
                    if (!$to_id && !$thanks && !$rthanks) {
                        $this->core->zero_dupe();
                        }
// Thanks for Posts extension

Clean your cache and then it should work.
Maybe a more talented one prepares a commit for the repository.

I used zero dupe with strict mode on, and redirect for ALL

**Comment by wcz-txp** [comment]
The original thanks_for_posts extension is here:
https://github.com/rxu/thanks_for_posts
