### ISSUE TITLE
phpbb 3.3 

### ISSUE THREAD

**Issue by ser** [phpbb-seo/usu#27]
phpbb 3.3 changed something and extension does not work at all :(

**Comment by bzozoo** [comment]
It seems It is an abandoned project

**Comment by meis2m** [comment]
https://github.com/phpbb-seo/usu/commit/6504f103831cbd46fe2982aeb40fc3cbd243d08c

**Comment by bzozoo** [comment]
> [6504f10](https://github.com/phpbb-seo/usu/commit/6504f103831cbd46fe2982aeb40fc3cbd243d08c)

Thank for fast reaction. I hope it will work on phpbb3.3

**Comment by tmartincpp** [comment]
Hello,

Thanks for the commit meis2m.

For the record there is at least one another change required by PHPBB 3.3.0; here is the patch : `--- phpbb32/ext/phpbbseo/usu/acp/usu.php	2019-10-31 07:01:34.000000000 +0100
+++ phpbb33/ext/phpbbseo/usu/acp/usu.php	2020-01-21 16:42:55.146005538 +0100
@@ -730,7 +730,7 @@ class usu
 					// Let's make sure that the proper field was added to the topic table
 					if ($config_name === 'sql_rewrite' && $config_value == 1 && !$this->core->seo_opt['sql_rewrite'])
 					{
-						$db_tools = new \phpbb\db\tools($this->db);
+						$db_tools = new \phpbb\db\tools\tools($this->db);
 						$db_tools->db->sql_return_on_error(true);
 
 						if (!$db_tools->sql_column_exists(TOPICS_TABLE, 'topic_url'))`

This allow to enable "Activate SQL Rewriting".
This patch is mandatory as phpbb/db/tools.php doesn't exist anymore in 3.3.0.

**Comment by meis2m** [comment]
> 
> 
> Hello,
> 
> Thanks for the commit meis2m.
> 
> For the record there is at least one another change required by PHPBB 3.3.0; here is the patch :
> 
> ```
> --- phpbb32/ext/phpbbseo/usu/acp/usu.php	2019-10-31 07:01:34.000000000 +0100
> +++ phpbb33/ext/phpbbseo/usu/acp/usu.php	2020-01-21 16:42:55.146005538 +0100
> @@ -730,7 +730,7 @@ class usu
>  					// Let's make sure that the proper field was added to the topic table
>  					if ($config_name === 'sql_rewrite' && $config_value == 1 && !$this->core->seo_opt['sql_rewrite'])
>  					{
> -						$db_tools = new \phpbb\db\tools($this->db);
> +						$db_tools = new \phpbb\db\tools\tools($this->db);
>  						$db_tools->db->sql_return_on_error(true);
>  
>  						if (!$db_tools->sql_column_exists(TOPICS_TABLE, 'topic_url'))
> ```
> 
> This allow to enable "Activate SQL Rewriting".
> This patch is mandatory as phpbb/db/tools.php doesn't exist anymore in 3.3.0.

Thank you bro
