### ISSUE TITLE
phpBB 3.3 SEO does not appear in ACP at Extensions

### ISSUE THREAD

**Issue by dealerexe** [phpbb-seo/usu#34]
Hello,
I want to install phpBB SEO Extension for phpBB 3.3 but the extension does not appear in ACP!

In ACP at Extensions PHPBB SEO does not appear - https://prnt.sc/rkn8hn
The files were uploaded to the /ext /phpbb folder - https://prnt.sc/rkn8s9

What in need to do?
Thanks!

**Comment by meis2m** [comment]
Hello
the path of files is:
phpbbseo/usu

**Comment by dealerexe** [comment]
> Hello
> the path of files is:
> phpbbseo/usu

Thanks a lot man, it works!

But, how I can remove that f4 (all „f” from URLs)? https://prnt.sc/rkrlnv

**Comment by meis2m** [comment]
u can change the setting in ACP - PHPBB SEO tab  ( remove forum id )
