### ISSUE TITLE
Undefined index: modrlinks_fr and modrforumlinks_fr

### ISSUE THREAD

**Issue by Skouat** [phpbb-seo/usu#4]
Hi there,

I installed your extension on a french testing board.

In ACP, there are the 4 following notices:

```
> [phpBB Debug] PHP Notice: in file [ROOT]/ext/phpbbseo/usu/acp/usu.php on line 1675: Undefined index: modrlinks_fr
> [phpBB Debug] PHP Notice: in file [ROOT]/ext/phpbbseo/usu/acp/usu.php on line 1676: Undefined index: modrforumlinks_fr
> [phpBB Debug] PHP Notice: in file [ROOT]/ext/phpbbseo/usu/acp/usu.php on line 1677: Undefined index: modrlinks_fr
> [phpBB Debug] PHP Notice: in file [ROOT]/ext/phpbbseo/usu/acp/usu.php on line 1678: Undefined index: modrforumlinks_fr
```

**Comment by meis2m** [comment]
Hello thank you

you can add this code into line: 1672

		$modrtype_lang['modrlinks_fr'] = array(
			1	=> 'http://www.phpbb-seo.org/simple-seo-url/simple-phpbb-seo-url-t1566.html',
			2	=> 'http://www.phpbb-seo.org/mixed-seo-url/mixed-phpbb-seo-url-t1565.html',
			3	=> 'http://www.phpbb-seo.org/advanced-seo-url/advanced-phpbb-seo-url-t1219.html',
			'u'	=> 'http://www.phpbb-seo.org/phpbb-mod-rewrite/ultimate-seo-url-t4608.html',
		);

		$modrtype_lang['modrforumlinks_fr'] = array(
			1	=> 'http://www.phpbb-seo.org/simple-seo-url/',
			2	=> 'http://www.phpbb-seo.or/mixed-seo-url/',
			3	=> 'http://www.phpbb-seo.org/advanced-seo-url/',
			'u'	=> 'http://www.phpbb-seo.org/phpbb-mod-rewrite/',
		);
