### ISSUE TITLE
phpBB version 3.2.4

### ISSUE THREAD

**Issue by utagawal** [phpbb-seo/usu#5]
Hello,

It seems the extension is not compatible with phpBB 3.2.4

In ACP error message :

[phpBB Debug] PHP Notice: in file [ROOT]/ext/phpbbseo/usu/acp/usu.php on line 140: Indirect modification of overloaded property phpbb/user::$lang has no effect

(using french languiage pack...)

In the forum itself when clicking on a sub forum :

No route found for "GET /name-of-the-sub-forum/" (from "https://websitename.com/forum/index.php?sid=70c9823eda050962b6baa6d76563720f")

**Comment by meis2m** [comment]
and if you not use "fr" language?

**Comment by utagawal** [comment]
I just tried. Same behavior. Does it work for you ?

**Comment by meis2m** [comment]
i'm not testing on 3.2.4 but it should be working. 3.2.5 will be released tomorrow i will test it on that.

**Comment by meis2m** [comment]
i tested in 3.2.5 and working

**Comment by Aspie96** [comment]
I am using 3.2.4 and I do not get this error.
