### ISSUE TITLE
Extension urls stay like original phpBB in the latest version when i update

### ISSUE THREAD

**Issue by zetrader** [phpbb-seo/usu#54]
Hi, if i update to the latest version (git updated 18th of July 2021), the urls of forums, topics and post are the original from PhpBB, like if the extension is not active, no matter how i update the htaccess, disable/enable the extension, change options...

If i disable, delete, and came back to the previous version of git (downloaded 13th of July 2021), extension urls display nice again, forums, topics, posts...

So there's a bug with the last update that corrects the XSS, i'm talking about this update :
https://github.com/phpbb-seo/usu/pull/53

The version downloaded before that (13th of july) doesn't make that bug.

**Comment by ser** [comment]
i think you must verify your installation - all works well with current master

**Comment by zetrader** [comment]
I have to reinstall the whole forum? As i said, if i delete the files of the extension and come back to the anterior version (downloaded 13th of july 2021), it works fine but i guess it has the vulnerability to reflected XSS attack.

**Comment by ser** [comment]
i do not know your environment, it works for me without any re-installation

**Comment by zetrader** [comment]
Ok, i've tried again with latest version (disable, delete files, upload latest version, enable), same bug, i've chosen the exact same options in the extension, changed nothing.
Coming back to previous version (disable, delete files, upload latest version, enable), choosing the exact same options in the extenssion, it works again.
I don't know where the bug can be, changing or not changing the .htaccess doesn't change anything, latest version does the bug, previous version does not.

**Comment by zetrader** [comment]
Ok i've tried with another domain name and directory, with a fresh new forum phpBB 3.3.4 (latest version), new database, and latest version of USU, still the same bug, urls are phpBB urls.
If i disable, delete and upload the previous version of USU with the same parameters : it works, urls are the good ones for forums, topics, posts.

**Comment by ser** [comment]
OK I did not not understood your initial bug report - you are correct, sorry :-) In current master urls are phpBB urls. It's clearly a bug.

**Comment by meis2m** [comment]
@marc1706 
Hello dear marc , have you any opinion?

**Comment by esginmurat** [comment]
Hello all. i have same problem :(
@ser @meis2m @zetrader
