### ISSUE TITLE
Rewrited urls contain port number

### ISSUE THREAD

**Issue by haloween** [phpbb-seo/usu#8]
My urls are being rewritten as domain:80 though connection is HTTPS.
It should be possible to disable that behaviour :/

**Comment by Aspie96** [comment]
Try to go to your settings in ACP in Server Configuration -> Server and delete the field "Server port", then submit.

**Comment by wbervoets** [comment]
@Aspie96 that works, thanks for the plugin

**Comment by Aspie96** [comment]
I did not create the plugin.
Anyways, if it works it should be marked as closed @haloween.
